### ISSUE TITLE
Impossible d'installer le CMS dans un sous dossier

### ISSUE THREAD

**Issue by FrBillyD** [magix-cms/magixcms#128]
Bonjour,

Il est apparemment impossible d'installer le CMS dans un sous répertoire. En effet, nous avons plusieurs interfaces à configurer et le CMS devrait être dans un sous dossier "portail". La redirection nous renvoi vers "monsiteweb.com/install/index.php" au lieux de "monsiteweb.com/portail/install/index.php".

Pouvez-vous faire quelque chose ? Y'a-t-il une option à changer quelque part ? Ou est-ce un bug ?

Merci d'avance pour les participant et les développeurs ! :+1:

**Comment by gtraxx** [comment]
Bonjour, le cms est conçu pour s'installer dans un dossier faisant office de root, donc pour monsiteweb.com il faut placer les fichiers en racine.
Par contre si vous désirez l'installer dans un dossier nommé "portail" il vous suffit de modifier les dns afin que dossier soit un sous domaine (donc il devient un root en quelque sorte)
Et le domaine serai donc : portal.monsiteweb.com :)
J'espère avoir répondu a votre question.

**Comment by FrBillyD** [comment]
Merci pour la réponse. En fait, j'avais bien compris cela, mais notre site est déjà le sous-domaine d'un sous-domaine et également pour un soucis d'organisation, nous préférons le mettre dans un sous dossier. Mais ce n'est pas grave, nous utiliserons un autre CMS peut-être plus adapté à nos besoins.

Merci encore pour la réponse (je suivrais tout de même le projet car il a l'air intéressant et suvi :smile:).
