### ISSUE TITLE
Ajout de tailles d'images supplémentaires

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms#130]
Ajout de tailles d'images supplémentaires dans les éléments suivants : 
### Catalogue
- category
  - medium
  - large
- subcategory
  - medium
  - large
- galery
  - medium
### news
- large

Génération des nouvelles tailles a l'upload + récupération dans le skin par défaut

**Comment by Xarksass** [comment]
N'oublie pas de mettre ça en place quand tu aura le temps ;)

**Comment by gtraxx** [comment]
@Xarksass Je regarde pour créer des tailles supplémentaires
