### ISSUE TITLE
Restructure du dossier img pour le catalogue

### ISSUE THREAD

**Issue by Xarksass** [magix-cms/magixcms#133]
Restructurer le dossier image sur base du nouveau système de base de donnée.
- catalog
  - c - `categorie`
    - 1 - `id catégorie`
      - s - `small`
      - m - `medium`
      - l - `large`
    - 2
    - 3
  - p - `produit`
    - 1 - `id produit`
      - g - `gallerie`
      - s - `small`
      - m - `medium`
      - l - `large`
    - 2
    - 3

**Comment by gtraxx** [comment]
Prévu dans magix cms 3
