### ISSUE TITLE
Problème à l'installation.

### ISSUE THREAD

**Issue by Frax25550** [magix-cms/magixcms#141]
Bonjour 
J'ai un message d'erreur sur l'index : 
Parse error: syntax error, unexpected T_NEW in /mnt/168/sdb/9/9/djeunzstation/lib/mcfrontend.php on line 53

Et je ne comprend absolument pas d'ou cela vient car je n'est encore pas lancer l'installation , du moins il met impossible de la lancer puisque j'ai ce message d'erreur .
Merci d'avance

**Comment by gtraxx** [comment]
Bonjour, pourriez-vous me donner votre version de PHP ainsi que la configuration ?
PS : n'oubliez pas qu'il faut un virtualhost en local !!
Merci

**Comment by Frax25550** [comment]
Bonjour je suis sur ftp Free . Alors je ne saurais pas vous répondre .

Envoyé de mon iPhone

Le 11 janv. 2017 à 08:35, Gérits Aurélien <notifications@github.com<mailto:notifications@github.com>> a écrit :


Bonjour, pourriez-vous me donner votre version de PHP ainsi que la configuration ?
PS : n'oubliez pas qu'il faut un virtualhost en local !!
Merci

**Comment by gtraxx** [comment]
Vous pouvez placer un php info à la racine pour avoir la configuration
http://php.net/manual/fr/function.phpinfo.php

**Comment by gtraxx** [comment]
Vous pouvez également tester un hébergement gratuit sur OVH
https://www.ovh.co.uk/domains/start10m_hosting_offer.xml

http://www.magix-cms.com/fr/catalogue/5-hebergements/ovh-14

**Comment by Frax25550** [comment]
Bonjour voici le descriptif:

[PHP Logo]<http://www.php.net/>
PHP Version 4.4.3-dev



System  Linux phpn11-g5.priv.free.fr
Build Date      Nov 5 2007 00:35:00
Server API      CGI/FastCGI
PHP API         20020918
PHP Extension   20020429
Zend Extension  20050606
Zend Memory Manager     enabled
Thread Safety   disabled
Registered PHP Streams  php, http, compress.bzip2, compress.zlib


Cela vous suffit t-il ?
________________________________
De : Gérits Aurélien <notifications@github.com>
Envoyé : mercredi 11 janvier 2017 10:51
À : magix-cms/magixcms
Cc : Frax25550; Author
Objet : Re: [magix-cms/magixcms] Problème à l'installation. (#141)


Vous pouvez placer un php info à la racine pour avoir la configuration
http://php.net/manual/fr/function.phpinfo.php

-

**Comment by gtraxx** [comment]
Bonjour, je vois que Free tourne sous PHP 4 :/ plus aucune application ne tourne sous cette version devenue obsolète.
Il faut au minimum  php 5.3

**Comment by Frax25550** [comment]
Et comment es-que je pourrait installer php 5.3 sur cette ftp ?

Envoyé de mon iPhone

Le 12 janv. 2017 à 14:52, Gérits Aurélien <notifications@github.com<mailto:notifications@github.com>> a écrit :


Bonjour, je vois que Free tourne sous PHP 4 :/ plus aucune application ne tourne sous cette version devenue obsolète.
Il faut au minimum php 5.3

**Comment by gtraxx** [comment]
Vous devez demander a Free s'ils ont php 5.3 minimum de disponible :)
