### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mcsteiner** [magix-cms/magixcms#143]
Bonjour,
Lors de  l'installation le test de connexion à la base de données est réussi, mais la création des tables tombent en échec. Voici le message : 
SQLSTATE[HY000] [2002] Connection refused 
Pouvez-vous m'aider ?
Marie

**Comment by gtraxx** [comment]
Bonjour, en faites le test de connexion ne crée pas le fichier de configuration sql mais seul le bouton "envoyer" (cela peu porter a confusion, nous changerons cela dans l'avenir)

**Comment by mcsteiner** [comment]
Bonjour
Oui j'avais bien compris cela. D'ailleurs j'ai vérifié,  le fichier de
configuration est ok sur le serveur. Mais ça ne marche pas.

Le 16 janv. 2017 15:26, "Gérits Aurélien" <notifications@github.com> a
écrit :

**Comment by gtraxx** [comment]
envoyer moi votre fichier config.php sur le mail suivant : support@magix-cms.com

**Comment by mcsteiner** [comment]
Je ne peux pas pour l'instant. Je le fais des que je le peux.

Le 16 janv. 2017 3:47 PM, "Gérits Aurélien" <notifications@github.com> a
écrit :

**Comment by gtraxx** [comment]
Pas de souci :)

**Comment by mcsteiner** [comment]
Voici le gichier config en pièce jointe

2017-01-16 16:26 GMT+01:00 Gérits Aurélien <notifications@github.com>:

**Comment by gtraxx** [comment]
Bonjour, je n'ai rien reçu pourriez-vous l'envoyer sur support@magix-cms.com
PS :  je pense que pour envoyer des fichiers php il faut simplement le zipper

**Comment by mcsteiner** [comment]
Bonjour,

J'ai transmis le fichier à support@magix-cms.com mais je n'ai toujours pas
de réponse.
L'avez-vous bien recu ?



Le 17 janvier 2017 à 11:39, Gérits Aurélien <notifications@github.com> a
écrit :
