### ISSUE TITLE
Impossible connexion au pannel admin

### ISSUE THREAD

**Issue by PilafSamp** [magix-cms/magixcms#144]
J'essaye de me connecter à l'administration sur le site "wyzone.xyz/admin" quand j'entre le mdp et le login il me dit qu'il est incorrect pourtant j'ai bien vérifié mes identifiants avant de l'inscrire à l'installation pourtant rien est quand je met l'adresse email à la place du pseudo il charge : 

Cette page ne fonctionne pas

Impossible de traiter cette demande via www.wyzone.xyz à l'heure actuelle.
HTTP ERROR 500

**Comment by gtraxx** [comment]
Bonjour, je viens de regarder mais il n'y a pas le cms sur votre serveur ?
Le login c'est toujours une adresse mail et non le pseudo

**Comment by PilafSamp** [comment]
Je l'ai enlevé mais j'ai essayé l'adresse email cela ne marchez pas.
